name: ci

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - docs/**
      - README.md
  pull_request:
    branches:
      - develop
    paths-ignore:
      - docs/**
      - README.md

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run lint
        run: ./gradlew lint
      - name: Run unit tests
        run: ./gradlew test
      - name: Set ANDROID_HOME
        run: |
          echo 'export ANDROID_HOME=/usr/local/lib/android/sdk/ >> ~/.zshrc'
          echo 'export PATH=$ANDROID_HOME/bin:$PATH >> ~/.zshrc'
      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86
          profile: pixel
          disable-animations: true
          script: ./gradlew connectedAndroidTest
