name: StoreScreenshot

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - docs/**
      - README.md

jobs:
  store-screenshot-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read # for clone
      actions: write # for upload-artifact

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # Better than caching and/or extensions of actions/setup-java
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper

      - name: record screenshot
        id: record-test
        run: |
          ./gradlew recordRoborazziDebug --stacktrace

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot
          path: |
            **/build/outputs/roborazzi
          retention-days: 30
